let ManropeBold = "Manrope-Bold"
let ManropeExtraBold = "Manrope-ExtraBold"
let ManropeSemiBold = "Manrope-SemiBold"
let ManropeRegular = "Manrope-Regular"
let TexGyreHerosBold = "TexGyreHeros-Bold"
let TextGyreHerosRegular = "TexGyreHeros-Regular"
